// export const productos = [{
//         "id": 1,
//         "categoria": "facial",
//         "subcategoria": "aguas",
//         "variedad": "aplicador",
//         "tipo": "rosas",
//         "nombre": "Agua de Rosas",
//         "precio": 700,
//         "img": "/media/aRosas.jpeg",
//         "stock": 100,
//         "descripcion": "BENEFICIOS DEL AGUA DE ROSAS: BALANCEA EL PH DE LA PIEL, ES ANTIOXIDANTE, REGENERA Y FORTALECE LOS TEJIDOS, ES ANTIINFLAMATORIA, REHIDRATA Y REFRESCA, REAFIRMA LA PIEL, ES ASTRINGENTE, LIMPIA Y CIERRA LOS POROS.",
//         "descripcion2": "Envase de vidrio con pulverizador, de 120ml."
//     },
//     {
//         "id": 2,
//         "categoria": "facial",
//         "subcategoria": "aguas",
//         "variedad": "aplicador",
//         "tipo": "hamamelis",
//         "nombre": "Agua de Hamamelis",
//         "precio": 750,
//         "img": "/media/aHamamelis.jpeg",
//         "stock": 100,
//         "descripcion": "BENEFICIOS DEL AGUA DE HAMAMELIS PARA EL ROSTRO: FUNCIÓN ASTRINGENTE (LIMPIA, CIERRA LOS POROS Y PREVIENE LA APARICIÓN DE PUNTOS NEGROS), FAVORECE LA REDUCCIÓN DE OJERAS, ES ANTINFLAMATORIA Y REDUCE LAS BOLSAS EN EL ÁREA DE LOS OJOS. PIERNAS CANSADAS: FAVORECE LA CIRCULACIÓN POR LO CUAL ES IDEAL PARA LA PREVENCIÓN DE VARICES Y ARAÑITAS.",
//         "descripcion2": "Envase de vidrio con pulverizador, de 120ml."
//     },
//     {
//         "id": 3,
//         "categoria": "facial",
//         "subcategoria": "aguas",
//         "variedad": "aplicador",
//         "tipo": "azahar",
//         "nombre": "Agua de Azahar",
//         "precio": 700,
//         "img": "/media/aAzahar.jpeg",
//         "stock": 100,
//         "descripcion": "Ideal para un cuidado integral gracias a sus propiedades astringentes, antisépticas y antioxidantes. Aporta elasticidad y regula la oleosidad natural de la piel.",
//         "descripcion2": "Envase de vidrio con pulverizador, de 120ml."
//     },
//     {
//         "id": 4,
//         "categoria": "capilar",
//         "subcategoria": "shampoo",
//         "variedad": "solido",
//         "tipo": "seco",
//         "nombre": "Shampoo: Cabello Seco",
//         "precio": 900,
//         "img": "/media/seco.jpeg",
//         "stock": 150,
//         "descripcion": "Humecta en profundidad el cabello y el cuero cabelludo, aliviando la resequedad. Ideal para cabellos maltratados, teñidos o con frizz.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Vegano. Cruelty Free, Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 5,
//         "categoria": "capilar",
//         "subcategoria": "shampoo",
//         "variedad": "solido",
//         "tipo": "fortalecedor",
//         "nombre": "Shampoo: Fortalecedor",
//         "precio": 900,
//         "img": "/media/fortalecedor.jpeg",
//         "stock": 150,
//         "descripcion": "Detiene la caída del cabello, favoreciendo la irrigaciòn sanguínea y el crecimiento capilar.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Vegano. Cruelty Free, Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 6,
//         "categoria": "capilar",
//         "subcategoria": "shampoo",
//         "variedad": "solido",
//         "tipo": "equilibrado",
//         "nombre": "Shampoo: Equilibrado",
//         "precio": 900,
//         "img": "/media/equilibrado.jpeg",
//         "stock": 150,
//         "descripcion": "COMPONENTES: Cocoil Isetionato de Sódio (tensioactivo natural derivado del coco), Aceite de coco, enriquecido con Manteca de Karité. Nutre e hidrata el cabello.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Vegano. Cruelty Free, Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 7,
//         "categoria": "capilar",
//         "subcategoria": "shampoo",
//         "variedad": "solido",
//         "tipo": "graso",
//         "nombre": "Shampoo: Cabello Graso/Anti-Caspa",
//         "precio": 900,
//         "img": "/media/graso.jpeg",
//         "stock": 150,
//         "descripcion": "Cocoil Isetionato de Sodio (tensioactivo natural derivado del coco), Aceite de coco, enriquecido con aceite de ricino y aceite esencial de limòn. Elimina la grasitud y barre la caspa.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Vegano. Cruelty Free, Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 8,
//         "categoria": "capilar",
//         "subcategoria": "acondicionador",
//         "variedad": "solido",
//         "tipo": "acondicionador",
//         "nombre": "Acondicionador",
//         "precio": 1000,
//         "img": "/media/acondicionador.jpeg",
//         "stock": 150,
//         "descripcion": "COMPONENTES: BTMS, Manteca de cacao, enriquecido con aceite de coco y aceite de jojoba. Nutre el cabello, dejándolo suave y sedoso de manera natural, sin efecto graso.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Vegano. Cruelty Free, Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 9,
//         "categoria": "capilar",
//         "subcategoria": "serum",
//         "variedad": "aplicador",
//         "tipo": "serum",
//         "nombre": "Serum Capilar",
//         "precio": 1100,
//         "img": "/media/serum.jpeg",
//         "stock": 100,
//         "descripcion": "COMPONENTES: Aceite de Argán, Aceite de Andiroba, Aceite Esencial de Neroli.",
//         "descripcion2": "Envase de vidrio reutilizable con dosificador. 27ml."
//     },
//     {
//         "id": 10,
//         "categoria": "corporal",
//         "subcategoria": "crema",
//         "variedad": "manos",
//         "tipo": "nutritiva",
//         "nombre": "Crema para Manos Nutritiva",
//         "precio": 700,
//         "img": "/media/creMan.jpeg",
//         "stock": 100,
//         "descripcion": "Orquídea & Lirio - Su textura ligera deja una sensación de suavidad con un agradable aroma floral. Presentacion bifloral de Orquídea & Lirio (también disponible en variedad Orquídea & Nardo).",
//         "descripcion2": "Producto vegano, libre de químicos y aceite de palma. Aprobado por ANMAT. Envase de vidrio de 45ml."
//     },
//     {
//         "id": 11,
//         "categoria": "corporal",
//         "subcategoria": "crema",
//         "variedad": "manos",
//         "tipo": "extra nutritiva",
//         "nombre": "Crema p/ Manos Extra-Nutri",
//         "precio": 750,
//         "img": "/media/creMan.jpeg",
//         "stock": 100,
//         "descripcion": "Orquídea & Nardo - Su textura ligera deja una sensación de suavidad con un agradable aroma floral. Presentacion bifloral de Orquídea & Nardo (también disponible en variedad Orquídea & Lirio).",
//         "descripcion2": "Producto vegano, libre de químicos y aceite de palma. Aprobado por ANMAT. Envase de vidrio de 45ml."
//     },
//     {
//         "id": 12,
//         "categoria": "corporal",
//         "subcategoria": "crema",
//         "variedad": "cuerpo",
//         "tipo": "nutritiva",
//         "nombre": "Crema Corporal Nutritiva",
//         "precio": 1250,
//         "img": "/media/creCor.jpeg",
//         "stock": 100,
//         "descripcion": "Su fórmula a base de Manteca de Karité y Aloe Vera, enriquecida con vitamina E, brinda un cuidado natural para vivir y sentir una piel saludable.",
//         "descripcion2": "Vegano, libre de químicos y aceite de palma. Aprobado por ANMAT. Envase de vidrio con válvula dosificadora de 150ml."
//     },
//     {
//         "id": 13,
//         "categoria": "corporal",
//         "subcategoria": "crema",
//         "variedad": "cuerpo",
//         "tipo": "extra nutritiva",
//         "nombre": "Crema Corporal Extra-Nutritiva",
//         "precio": 1350,
//         "img": "/media/creCorN.jpeg",
//         "stock": 100,
//         "descripcion": "Brinda nutrición y suavidad. De fácil absorción, deja la piel tersa y perfumada.",
//         "descripcion2": "Producto vegano, libre de químicos y aceite de palma. Aprobado por ANMAT. Envase de vidrio con válvula dosificadora de 150ml."
//     },
//     {
//         "id": 14,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "exfoliante",
//         "tipo": "mentolado",
//         "nombre": "Jabón Exfoliante Mentolado",
//         "precio": 650,
//         "img": "/media/jabonExf.jpeg",
//         "stock": 300,
//         "descripcion": "Elaborado con Aceite de Coco y Aceite de Oliva Orgánico, junto a la acción exfoliante de las SEMILLAS DE AMARANTO, deja la piel suave, libre de impurezas.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Cruelty Free & Vegano. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 15,
//         "categoria": "corporal",
//         "subcategoria": "pasta dental",
//         "variedad": "vidrio",
//         "tipo": "eucalipto",
//         "nombre": "Pasta dental de Eucalipto",
//         "precio": 550,
//         "img": "/media/pastaDental.jpeg",
//         "stock": 100,
//         "descripcion": "COMPONENTES: Arcilla blanca o Caolín. Bicarbonato de sodio: Blanquea de manera natural los dientes, alcaliniza la cavidad bucal.",
//         "descripcion2": "Aceite de coco, Aceite Escencial de Tea Tree: Combate el mal aliento, reduce la inflamación y elimina bacterias."
//     },
//     {
//         "id": 16,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "esenciales",
//         "tipo": "tilo",
//         "nombre": "Jabón Esencial de Tilo",
//         "precio": 400,
//         "img": "/media/jabones.jpeg",
//         "stock": 300,
//         "descripcion": "JABONES VEGETALES - LINEA ESENCIAL están elaborados con aceite de coco. Limpian e hidratan la piel de manera natural y delicada.",
//         "descripcion2": "PESO: 100grs. Biodegradable. Vegano. Cruelty Free. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 17,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "esenciales",
//         "tipo": "oleo 31",
//         "nombre": "Jabón Esencial de Oleo 31",
//         "precio": 400,
//         "img": "/media/jabones.jpeg",
//         "stock": 300,
//         "descripcion": "JABONES VEGETALES - LINEA ESENCIAL están elaborados con aceite de coco. Limpian e hidratan la piel de manera natural y delicada.",
//         "descripcion2": "PESO: 100grs. Biodegradable. Vegano. Cruelty Free. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 18,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "esenciales",
//         "tipo": "coco",
//         "nombre": "Jabón Esencial de Coco",
//         "precio": 400,
//         "img": "/media/jabones.jpeg",
//         "stock": 300,
//         "descripcion": "JABONES VEGETALES - LINEA ESENCIAL están elaborados con aceite de coco. Limpian e hidratan la piel de manera natural y delicada.",
//         "descripcion2": "PESO: 100grs. Biodegradable. Vegano. Cruelty Free. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 19,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "especiales",
//         "tipo": "calendula",
//         "nombre": "Jabón Esencial de Caléndula",
//         "precio": 550,
//         "img": "/media/jabCal.jpeg",
//         "stock": 300,
//         "descripcion": "Ideal para pieles sensibles y para todo tipo de piel en general. Gracias a las propiedades cicatrizantes y regenerativas de la Caléndula, ésta variedad es la aliada natural para cuidar naturalmente la piel.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Cruelty Free & Vegano. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 20,
//         "categoria": "corporal",
//         "subcategoria": "jabon",
//         "variedad": "especiales",
//         "tipo": "jazmin",
//         "nombre": "Jabón Esencial de Jazmín",
//         "precio": 550,
//         "img": "/media/jabJaz.jpeg",
//         "stock": 300,
//         "descripcion": "Ideal para todo tipo de piel. Gracias a las propiedades del Jazmín, este jabón es súper hidratante y su agradable aroma favorece la relajación mental y mejora el estado de ánimo.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 100grs. Biodegradable. Cruelty Free & Vegano. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA."
//     },
//     {
//         "id": 21,
//         "categoria": "corporal",
//         "subcategoria": "pasta dental",
//         "variedad": "vidrio",
//         "tipo": "citrico",
//         "nombre": "Pasta dental Cítrica",
//         "precio": 550,
//         "img": "/media/pastaDental.jpeg",
//         "stock": 100,
//         "descripcion": "COMPONENTES: Arcilla blanca o Caolín. Bicarbonato de sodio: Blanquea de manera natural los dientes, alcaliniza la cavidad bucal.",
//         "descripcion2": "Aceite de coco, Aceite Escencial de Tea Tree: Combate el mal aliento, reduce la inflamación y elimina bacterias."
//     },
//     {
//         "id": 22,
//         "categoria": "corporal",
//         "subcategoria": "desodorante",
//         "variedad": "vidrio",
//         "tipo": "mix foral",
//         "nombre": "Desodorante Mix Floral",
//         "precio": 600,
//         "img": "/media/desodorante.jpeg",
//         "stock": 150,
//         "descripcion": "FÓRMULA MAS SUAVE Y CREMOSA - Protege la piel de las axilas, gracias a su textura cremosa, manteniendolas suaves y con un agradable aroma.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 60grs. Vegano. Cruelty Free. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA. Envase de vidrio."
//     },
//     {
//         "id": 23,
//         "categoria": "corporal",
//         "subcategoria": "desodorante",
//         "variedad": "vidrio",
//         "tipo": "lavanda",
//         "nombre": "Desodorante Lavanda",
//         "precio": 600,
//         "img": "/media/desodorante.jpeg",
//         "stock": 150,
//         "descripcion": "FÓRMULA MAS SUAVE Y CREMOSA - Protege la piel de las axilas, gracias a su textura cremosa, manteniendolas suaves y con un agradable aroma.",
//         "descripcion2": "PRODUCTO APROBADO POR ANMAT. PESO: 60grs. Vegano. Cruelty Free. Libre de químicos, sulfatos y parabenos. SIN ACEITE DE PALMA. Envase de vidrio."
//     },
//     {
//         "id": 24,
//         "categoria": "accesorios",
//         "subcategoria": "peines",
//         "variedad": "madera",
//         "tipo": "simple",
//         "nombre": "Peine para Cabello",
//         "precio": 650,
//         "img": "/media/peineMadera.jpeg",
//         "stock": 100,
//         "descripcion": "PEINES DE MADERA MACIZA DE PARAISO CON MANGO, SIN MANGO, PARA RULOS. NO GENERA ESTATICA.",
//         "descripcion2": "SIN TRATAMIENTO QUÍMICO NI CERAS. ANTIFRIZZ."
//     },
//     {
//         "id": 25,
//         "categoria": "accesorios",
//         "subcategoria": "peines",
//         "variedad": "madera",
//         "tipo": "cabello seco",
//         "nombre": "Peine para Cabello Seco",
//         "precio": 900,
//         "img": "/media/peineSeco.jpeg",
//         "stock": 50,
//         "descripcion": "MADERA DE PALO BLANCO Elaborado con filamentos biodegradables, ideal para usar sobre el cabello seco. ANTIFRIZZ.",
//         "descripcion2": "MEDIDAS: 19,5x4cm."
//     },
//     {
//         "id": 26,
//         "categoria": "accesorios",
//         "subcategoria": "peines",
//         "variedad": "madera",
//         "tipo": "cabello humedo",
//         "nombre": "Peine para Cabello Húmedo",
//         "precio": 1000,
//         "img": "/media/peineHumedo.jpeg",
//         "stock": 50,
//         "descripcion": "MADERA DE PALO BLANCO. Cada terminación presenta su punta protegida para favorecer el desenredado del cabello mojado.",
//         "descripcion2": "MEDIDAS: 19,5x4cm."
//     },
//     {
//         "id": 27,
//         "categoria": "accesorios",
//         "subcategoria": "esponja",
//         "variedad": "vegetal",
//         "tipo": "exfoliante",
//         "nombre": "Esponja Veg. Exfoliante",
//         "precio": 150,
//         "img": "/media/espVeg.jpeg",
//         "stock": 200,
//         "descripcion": "KIT DE 3 RUEDAS DE ESPONJA VEGETAL - La esponja vegetal o Luffa (nombre que recibe la planta) es la alternativa ideal para cuidar y limpiar la piel de manera natural.",
//         "descripcion2": "100% fibras vegetales."
//     },
//     {
//         "id": 28,
//         "categoria": "accesorios",
//         "subcategoria": "cepillo",
//         "variedad": "madera",
//         "tipo": "exfoliante",
//         "nombre": "Cepillo Corporal Exfoliante",
//         "precio": 800,
//         "img": "/media/cepExf.jpeg",
//         "stock": 100,
//         "descripcion": "MADERA DE PALO BLANCO Y FILAMENTOS BIODEGRADABLES - El cepillado en seco tiene múltiples beneficios para nuestra salud y bienestar: Estimula el sistema circulatorio, favoreciendo una adecuada circulación sanguínea.",
//         "descripcion2": "CON CORDÓN DE ALGODÓN - MEDIDAS: 18x6cm."
//     },
//     {
//         "id": 29,
//         "categoria": "accesorios",
//         "subcategoria": "cepillo",
//         "variedad": "bambu",
//         "tipo": "dental",
//         "nombre": "Cepillo de dientes",
//         "precio": 400,
//         "img": "/media/cepDental.jpeg",
//         "stock": 300,
//         "descripcion": "Es 97% Biodegradable. Vida útil y calidad. Diseño estético.",
//         "descripcion2": "Sustentable. El precio corresponde a 1 unidad"
//     },
//     {
//         "id": 30,
//         "categoria": "accesorios",
//         "subcategoria": "porta cepillo",
//         "variedad": "bambu",
//         "tipo": "doble",
//         "nombre": "Porta Cepillo de dientes Doble",
//         "precio": 800,
//         "img": "/media/portaCep.jpeg",
//         "stock": 100,
//         "descripcion": "Capacidad para dos cepillos de dientes. Confeccionada con elevación y agujeros posteriores para drenar el agua.",
//         "descripcion2": "MEDIDAS: 9x8x3cm."
//     },
//     {
//         "id": 31,
//         "categoria": "accesorios",
//         "subcategoria": "porta cepillo",
//         "variedad": "bambu",
//         "tipo": "portable",
//         "nombre": "Estuche Cepillo de Dientes",
//         "precio": 900,
//         "img": "/media/estucheCep.jpeg",
//         "stock": 200,
//         "descripcion": "Una manera práctica y sustentable de transportar el cepillo de dientes. Confeccionado 100% con bambú. Se recomienda no dejar en contacto con el agua o en ambientes húmedos.",
//         "descripcion2": "Vegano. Biodegradable. Vida útil y calidad. Diseño estético. Sustentable. MEDIDAS: 21x2,5cm."
//     },
//     {
//         "id": 32,
//         "categoria": "accesorios",
//         "subcategoria": "jabonera",
//         "variedad": "bambu",
//         "tipo": "doble",
//         "nombre": "Jabonera Doble",
//         "precio": 700,
//         "img": "/media/jabonera.jpeg",
//         "stock": 150,
//         "descripcion": "JABONERA DE MADERA CURADA - Capacidad para dos pastillas de shampoo sólido/jabón.",
//         "descripcion2": "Medidas: 17 x 9.5 cm."
//     },
//     {
//         "id": 33,
//         "categoria": "otros",
//         "subcategoria": "almohadilla",
//         "variedad": "semillas",
//         "tipo": "chica",
//         "nombre": "Almohadilla de Semillas Chica",
//         "precio": 1100,
//         "img": "/media/almChica.jpeg",
//         "stock": 50,
//         "descripcion": "Las almohadillas MULTIUSO CHICAS son versátiles y alivian diversos malestares: OJOS HINCHADOS ,CEFALEAS, NEURALGIAS, DOLOR DE MUELA, DOLORES MENSTRUALES, REDUCEN LA FIEBRE, ALIVIAN CONTRACTURAS Y DOLENCIAS EN ÁREAS LOCALIZADAS DEL CUERPO.",
//         "descripcion2": "MEDIDA: 22x11cm. PESO: 230grs."
//     },
//     {
//         "id": 34,
//         "categoria": "otros",
//         "subcategoria": "almohadilla",
//         "variedad": "semillas",
//         "tipo": "grande",
//         "nombre": "Almohadilla de Semillas Gde.",
//         "precio": 1550,
//         "img": "/media/almGrande.jpeg",
//         "stock": 50,
//         "descripcion": "Las almohadillas MULTIUSO GRANDES son versátiles y alivian diversos malestares: DOLOR LUMBAR, DOLOR CERVICAL, PIERNAS CANSADAS, ÁREAS EXTENSAS DEL CUERPO.",
//         "descripcion2": "MEDIDA: 45x16cm. PESO: 540grs."
//     }
// ];

// export const getFetch = new Promise((resolve, reject) => {

//     let url = 'flor.com';

//     if (url === 'flor.com') {
//         setTimeout(() => {
//             resolve(productos);
//         }, 1000);

//     } else {
//         reject("404 not found")
//     }
// });